In [2]:
import pandas as pd

df_african_cup_matches = pd.read_csv('Africa Cup of Nations Matches.csv')
display(df_african_cup_matches.head(3))

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
0,1957,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0
1,1957,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN
2,1957,16-Feb-57,NaN,Egypt,Ethiopia,4.0,0.0,Final,NaN,Municipal Stadium,Khartoum,30000.0

# Working with missing data with pandas

## 1. DataFrame.isna()

In [3]:
df_african_cup_matches.isna()

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
0,False,False,True,False,False,False,False,False,True,False,False,False
1,False,False,True,False,False,True,True,False,False,True,True,True
2,False,False,True,False,False,False,False,False,True,False,False,False
3,False,False,True,False,False,False,False,False,True,False,False,False
4,False,False,True,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
617,False,False,False,False,False,False,False,False,True,False,False,False
618,False,False,False,False,False,False,False,False,False,False,False,False
619,False,False,False,False,False,False,False,False,True,False,False,False
620,False,False,False,False,False,False,False,False,True,False,False,False
621,False,False,False,False,False,False,False,False,True,False,False,False

## 2.df.notna()

In [4]:
df_african_cup_matches.notna()

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
0,True,True,False,True,True,True,True,True,False,True,True,True
1,True,True,False,True,True,False,False,True,True,False,False,False
2,True,True,False,True,True,True,True,True,False,True,True,True
3,True,True,False,True,True,True,True,True,False,True,True,True
4,True,True,False,True,True,True,True,True,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...
617,True,True,True,True,True,True,True,True,False,True,True,True
618,True,True,True,True,True,True,True,True,True,True,True,True
619,True,True,True,True,True,True,True,True,False,True,True,True
620,True,True,True,True,True,True,True,True,False,True,True,True
621,True,True,True,True,True,True,True,True,False,True,True,True

## 3. df.notna() and df.notnull()

In [5]:
df_african_cup_matches.notna()
df_african_cup_matches.notnull()

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
0,True,True,False,True,True,True,True,True,False,True,True,True
1,True,True,False,True,True,False,False,True,True,False,False,False
2,True,True,False,True,True,True,True,True,False,True,True,True
3,True,True,False,True,True,True,True,True,False,True,True,True
4,True,True,False,True,True,True,True,True,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...
617,True,True,True,True,True,True,True,True,False,True,True,True
618,True,True,True,True,True,True,True,True,True,True,True,True
619,True,True,True,True,True,True,True,True,False,True,True,True
620,True,True,True,True,True,True,True,True,False,True,True,True
621,True,True,True,True,True,True,True,True,False,True,True,True

## 4. df.dropna()

In [6]:
df_african_cup_matches.dropna()

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
315,1998,21-Feb-98,17:00,Tunisia,Burkina Faso,1.0,1.0,Quarterfinals,Burkina Faso win on Penalities 7-8,Stade du 4-Août,Ouagadougou,35000.0
316,1998,21-Feb-98,20:00,Ivory Coast,Egypt,0.0,0.0,Quarterfinals,Egypt win on Penalities 4-5,Stade Municipal,Ouagadougou,20000.0
318,1998,25-Feb-98,16:00,DR Congo,South Africa,1.0,2.0,Semifinals,win after extra time,Stade du 4-Août,Ouagadougou,4000.0
320,1998,27-Feb-98,16:00,DR Congo,Burkina Faso,4.0,4.0,Third place match,DR Congo win on Penalities 4-1,Stade Municipal,Ouagadougou,25000.0
349,2000,7-Feb-00,19:00,Nigeria,Senegal,2.0,1.0,Quarterfinals,win after extra time,National Stadium,Lagos,60000.0
352,2000,12-Feb-00,16:00,South Africa,Tunisia,2.0,2.0,Third place match,South Africa win on Penalities 4-3,Accra Sports Stadium,Accra,1000.0
353,2000,13-Feb-00,16:00,Nigeria,Cameroon,2.0,2.0,Final,Cameroon win on Penalities 3-4,National Stadium,Lagos,60000.0
382,2002,7-Feb-02,16:00,Nigeria,Senegal,1.0,2.0,Semifinals,win after extra time,Stade Modibo Keïta,Bamako,20000.0
385,2002,10-Feb-02,16:00,Senegal,Cameroon,0.0,0.0,Final,Cameroon win on Penalities 2-3,Stade du 26 Mars,Bamako,50000.0
413,2004,8-Feb-04,17:00,Morocco,Algeria,3.0,1.0,Quarter-finals,win after extra time,Stade Taïeb El Mhiri,Sfax,22000.0
414,2004,11-Feb-04,16:00,Tunisia,Nigeria,1.0,1.0,Semi-finals,Tunisia win on Penalities 5-3,Stade 7 Novembre,Radès,56000.0
444,2006,4-Feb-06,15:00,Nigeria,Tunisia,1.0,1.0,Quarter-finals,Nigeria win on Penalities 6-5,Port Said Stadium,Port Said,10000.0
445,2006,4-Feb-06,19:00,Cameroon,Ivory Coast,1.0,1.0,Quarter-finals,Ivory Coast win on Penalities 11-12,Cairo Military Academy Stadium,Cairo,4000.0
449,2006,10-Feb-06,18:00,Egypt,Ivory Coast,0.0,0.0,Final,Egypt win on Penalities 4-2,Cairo International Stadium,Cairo,74100.0
477,2008,4-Feb-08,20:30,Tunisia,Cameroon,2.0,3.0,Quarter-finals,win after extra time,Tamale Stadium,Tamale,15000.0
507,2010,24-Jan-10,20:30,Ivory Coast,Algeria,2.0,3.0,Quarter-finals,win after extra time,Estádio do Chiazi,Cabinda,10000.0
508,2010,25-Jan-10,17:00,Egypt,Cameroon,3.0,1.0,Quarter-finals,win after extra time,Estádio Nacional de Ombaka,Benguela,12000.0
509,2010,25-Jan-10,20:30,Zambia,Nigeria,0.0,0.0,Quarter-finals,Nigeria win on Penalities 4-5,Estádio Nacional da Tundavala,Lubango,10000.0
516,2012,5-Feb-12,17:00,Gabon,Mali,1.0,1.0,Quarterfinals,Mali win on Penalities 4-5,Stade d'Angondjé,Libreville,30000.0
517,2012,5-Feb-12,20:00,Ghana,Tunisia,2.0,1.0,Quarterfinals,win after extra time,Stade de Franceville,Franceville,8000.0
521,2012,12-Feb-12,20:30[note 1],Zambia,Ivory Coast,0.0,0.0,Final,Zambia win on Penalities 8-7,Stade d'Angondjé,Libreville,40000.0
523,2013,2-Feb-13,20:30,South Africa,Mali,1.0,1.0,Quarter-finals,Mali win on Penalities 1-3,Moses Mabhida Stadium,Durban,45000.0
525,2013,3-Feb-13,20:30,Burkina Faso,Togo,1.0,0.0,Quarter-finals,win after extra time,Mbombela Stadium,Nelspruit,27000.0
527,2013,6-Feb-13,20:30,Burkina Faso,Ghana,1.0,1.0,Semi-finals,Burkina Faso win on Penalities 3-2,Mbombela Stadium,Nelspruit,35000.0
531,2015,31-Jan-15,20:30,Tunisia,Equatorial Guinea,1.0,2.0,Quarter-finals,win after extra time,Estadio de Bata,Bata,41000.0
537,2015,8-Feb-15,20:00,Ivory Coast,Ghana,0.0,0.0,Final,Ivory Coast win on Penalities 9-8,Estadio de Bata,Bata,32857.0
606,2019,5 July 2019 (2019-07-05),18:00,Morocco,Benin,1.0,1.0,Round of 16,Benin win on Penalities 1-4,Al Salam Stadium,Cairo,7500.0
610,2019,7 July 2019 (2019-07-07),18:00,Madagascar,DR Congo,2.0,2.0,Round of 16,Madagascar win on Penalities 4-2,Alexandria Stadium,Alexandria,5890.0
613,2019,8 July 2019 (2019-07-08),21:00,Ghana,Tunisia,1.0,1.0,Round of 16,Tunisia win on Penalities 4-5,Ismailia Stadium,Ismailia,8890.0
616,2019,11 July 2019 (2019-07-11),18:00,Ivory Coast,Algeria,1.0,1.0,Quarter-finals,Algeria win on Penalities 3-4,Suez Stadium,Suez,8233.0
618,2019,14 July 2019 (2019-07-14),18:00,Senegal,Tunisia,1.0,0.0,Semi-finals,win after extra time,30 June Stadium,Cairo,9143.0

In [26]:
print("===> With inplace=False")
display(type(df_african_cup_matches.dropna()))
print("===> With inplace=True")
display(type(df_african_cup_matches.dropna(inplace=True)))

===> With inplace=False

pandas.core.frame.DataFrame

===> With inplace=True

NoneType

## 5. df.interpolate()

In [14]:
df_african_cup_matches.interpolate()

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
0,1957,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0
1,1957,10-Feb-57,NaN,Ethiopia,South Africa,2.5,1.0,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,30000.0
2,1957,16-Feb-57,NaN,Egypt,Ethiopia,4.0,0.0,Final,NaN,Municipal Stadium,Khartoum,30000.0
3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
4,1959,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,20000.0
...,...,...,...,...,...,...,...,...,...,...,...,...
617,2019,11 July 2019 (2019-07-11),21:00,Madagascar,Tunisia,0.0,3.0,Quarter-finals,NaN,Al Salam Stadium,Cairo,7568.0
618,2019,14 July 2019 (2019-07-14),18:00,Senegal,Tunisia,1.0,0.0,Semi-finals,win after extra time,30 June Stadium,Cairo,9143.0
619,2019,14 July 2019 (2019-07-14),21:00,Algeria,Nigeria,2.0,1.0,Semi-finals,NaN,Cairo International Stadium,Cairo,49775.0
620,2019,17 July 2019 (2019-07-17),21:00,Tunisia,Nigeria,0.0,1.0,Third place play-off,NaN,Al Salam Stadium,Cairo,6340.0
621,2019,19 July 2019 (2019-07-19),21:00,Senegal,Algeria,0.0,1.0,Final,NaN,Cairo International Stadium,Cairo,75000.0

# nlargest and nsmallest()

# Values_count